pdf: about-stress-test.tex A-Simplified-Git.tex introduction-to-command.tex introduction-to-module.tex SJTU_BLUE.png figure_1.png figure_2.png
	xelatex A-Simplified-Git.tex
	xelatex A-Simplified-Git.tex
	xelatex A-Simplified-Git.tex
	xelatex A-Simplified-Git.tex



clean:
	-rm -rf *.aux
	-rm -rf *.gz
	-rm -rf *.toc
	-rm -rf *.log
	-rm -rf *.out